---
- name: Initialize shc config
  ansible.builtin.command: "{{ splunk_home }}/bin/splunk init shcluster-config -auth {{ splunk_auth }} -mgmt_uri https://{{ splunk_mgmt_uri }}:{{ splunkd_port }} -replication_port {{ splunk_shc_rep_port }} -replication_factor {{ splunk_shc_rf }} -conf_deploy_fetch_url https://{{ splunk_shc_deployer }}:{{ splunkd_port }} -secret {{ splunk_shc_key }} -shcluster_label {{ splunk_shc_label }}"
  become: true
  become_user: "{{ splunk_nix_user }}"
  register: shc_init_result
  changed_when: shc_init_result.rc == 0
  failed_when: shc_init_result.rc != 0
  notify: restart splunk
  no_log: false
  
- name: Disable Monitoring Console for shc member
  ansible.builtin.command: "{{ splunk_home }}/bin/splunk disable app splunk_monitoring_console -auth {{ splunk_auth }}"
  become: true
  become_user: "{{ splunk_nix_user }}"
  notify: restart splunk
  no_log: false

- name: Add index cluster as search peer
  ansible.builtin.command: "{{ splunk_home }}/bin/splunk edit cluster-config -mode searchhead -manager_uri https://{{ splunk_uri_cm }} -secret {{ splunk_idxc_key }} -auth admin:{{ splunk_admin_password }}"
  become: true
  become_user: "{{ splunk_nix_user }}"
  register: shc_init_result
  changed_when: shc_init_result.rc == 0 or shc_init_result.rc == 22
  failed_when: shc_init_result.rc != 0 and shc_init_result.rc != 22
  notify: restart splunk
  no_log: false

- name: Disable indexing for shc member
  community.general.ini_file:
    path: "{{ splunk_home }}/etc/system/local/outputs.conf"
    section: indexAndForward
    option: index
    value: false
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: "0644"
  become: true
  notify: restart splunk

- name: Include task forward internal logs
  ansible.builtin.include_tasks: configure_forward_internal_logs.yml
  when: ansible_host in groups['search']