---
#Uncomment if using the splunk.secret methods for the pass4symmkey in this playbook.
#- name: Extract encrypted value
#  ansible.builtin.include_tasks: check_decrypted_secret.yml
#  vars:
#    req_secret_conf: server
#    req_secret_section: shclustering
#    req_secret_option: pass4SymmKey

- name: Configure pass4SymmKey in  shclustering stanza for deployer
  community.general.ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: shclustering
    option: pass4SymmKey
    value: "{{ splunk_shc_key }}"
    mode: "0644"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
  become: true
  notify: restart splunk
  no_log: false
#  when: encrypted_secret_value.stdout == "" or (splunk_shc_key != decrypted_secret_value.stdout | default(''))

- name: Configure shcluster_label in shclustering stanza for deployer
  community.general.ini_file:
    path: "{{ splunk_home }}/etc/system/local/server.conf"
    section: shclustering
    option: shcluster_label
    value: "{{ splunk_shc_label }}"
    mode: "0644"
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
  become: true
  notify: restart splunk

- name: Disable Monitoring Console for shc manager
  ansible.builtin.command: "{{ splunk_home }}/bin/splunk disable app splunk_monitoring_console -auth {{ splunk_auth }}"
  become: true
  become_user: "{{ splunk_nix_user }}"
  notify: restart splunk
  no_log: false
  retries: 6
  delay: 5

- name: Disable indexing for shc deployer
  community.general.ini_file:
    path: "{{ splunk_home }}/etc/system/local/outputs.conf"
    section: indexAndForward
    option: index
    value: false
    owner: "{{ splunk_nix_user }}"
    group: "{{ splunk_nix_group }}"
    mode: "0644"
  become: true
  notify: restart splunk

- name: Include task forward internal logs
  ansible.builtin.include_tasks: configure_forward_internal_logs.yml