---
# Example playbook to perform either a splunk installation or upgrade of the UFs
- hosts:
    - uf
  roles:
    - ../roles/splunk
  vars:
    deployment_task: check_splunk.yml

- hosts:
    - uf
  roles:
    - ../roles/splunk
  vars:
    deployment_task: configure_deploymentclient.yml